openapi: 3.1.0
info:
  title: amp
paths:
  /workspaces/{workspaceId}/alertmanager/definition:
    PUT:
      summary: PutAlertManagerDefinition
      description: >-
        <p>Updates an existing alert manager definition in a workspace. If the
        workspace does not already have an alert manager definition, don't use
        this operation to create it. Instead, use
        <code>CreateAlertManagerDefinition</code>.</p>
      tags:
        - Put
        - Alerts
        - Managers
        - Definitions
        - Identifiers
        - Alert Management
        - Definitions
  /workspaces/{workspaceId}/logging:
    PUT:
      summary: UpdateLoggingConfiguration
      description: >-
        <p>Updates the log group ARN or the workspace ID of the current logging
        configuration.</p>
      tags:
        - Update
        - Logging
        - Configurations
        - Identifiers
        - Alert Management
        - Definitions
        - Logging
  /workspaces/{workspaceId}/rulegroupsnamespaces:
    GET:
      summary: ListRuleGroupsNamespaces
      description: <p>Returns a list of rule groups namespaces in a workspace.</p>
      tags:
        - Lists
        - Rules
        - Groups
        - Namespaces
        - Identifiers
        - Alert Management
        - Definitions
        - Logging
        - Rule Groups Namespaces
  /scrapers:
    GET:
      summary: ListScrapers
      description: >-
        <p>The <code>ListScrapers</code> operation lists all of the scrapers in
        your account. This includes scrapers being created or deleted. You can
        optionally filter the returned list.</p>
      tags:
        - Lists
        - Scrapers
        - Identifiers
        - Alert Management
        - Definitions
        - Logging
        - Rule Groups Namespaces
        - Scrapers
  /workspaces:
    GET:
      summary: ListWorkspaces
      description: >-
        <p>Lists all of the Amazon Managed Service for Prometheus workspaces in
        your account. This includes workspaces being created or deleted. </p>
      tags:
        - Lists
        - Workspaces
        - Identifiers
        - Alert Management
        - Definitions
        - Logging
        - Rule Groups Namespaces
        - Scrapers
        - Workspaces
  /workspaces/{workspaceId}/rulegroupsnamespaces/{name}:
    PUT:
      summary: PutRuleGroupsNamespace
      description: >-
        <p>Updates an existing rule groups namespace within a workspace. A rule
        groups namespace is associated with exactly one rules file. A workspace
        can have multiple rule groups namespaces.</p> <p>Use this operation only
        to update existing rule groups namespaces. To create a new rule groups
        namespace, use <code>CreateRuleGroupsNamespace</code>.</p> <p>You can't
        use this operation to add tags to an existing rule groups namespace.
        Instead, use <code>TagResource</code>.</p>
      tags:
        - Put
        - Rules
        - Groups
        - Namespaces
        - Identifiers
        - Alert Management
        - Definitions
        - Logging
        - Rule Groups Namespaces
        - Scrapers
        - Workspaces
        - Names
  /scrapers/{scraperId}:
    GET:
      summary: DescribeScraper
      description: >-
        <p>The <code>DescribeScraper</code> operation displays information about
        an existing scraper.</p>
      tags:
        - Describe
        - Scrapers
        - Identifiers
        - Alert Management
        - Definitions
        - Logging
        - Rule Groups Namespaces
        - Scrapers
        - Workspaces
        - Names
  /workspaces/{workspaceId}:
    GET:
      summary: DescribeWorkspace
      description: <p>Returns information about an existing workspace. </p>
      tags:
        - Describe
        - Workspaces
        - Identifiers
        - Alert Management
        - Definitions
        - Logging
        - Rule Groups Namespaces
        - Scrapers
        - Workspaces
        - Names
  /scraperconfiguration:
    GET:
      summary: GetDefaultScraperConfiguration
      description: >-
        <p>The <code>GetDefaultScraperConfiguration</code> operation returns the
        default scraper configuration used when Amazon EKS creates a scraper for
        you.</p>
      tags:
        - Get
        - Default
        - Scrapers
        - Configurations
        - Identifiers
        - Alert Management
        - Definitions
        - Logging
        - Rule Groups Namespaces
        - Scrapers
        - Workspaces
        - Names
        - Scraper Configurations
  /tags/{resourceArn}:
    DELETE:
      summary: UntagResource
      description: >-
        <p>Removes the specified tags from an Amazon Managed Service for
        Prometheus resource. The only resources that can be tagged are
        workspaces and rule groups namespaces. </p>
      tags:
        - Untag
        - Resources
        - Identifiers
        - Alert Management
        - Definitions
        - Logging
        - Rule Groups Namespaces
        - Scrapers
        - Workspaces
        - Names
        - Scraper Configurations
        - ARN
  /workspaces/{workspaceId}/alias:
    POST:
      summary: UpdateWorkspaceAlias
      description: <p>Updates the alias of an existing work
      tags:
        - Update
        - Workspaces
        - Alias
        - Identifiers
        - Alert Management
        - Definitions
        - Logging
        - Rule Groups Namespaces
        - Scrapers
        - Workspaces
        - Names
        - Scraper Configurations
        - ARN
        - Ali
