openapi: 3.1.0
info:
  title: amp
paths:
  /workspaces/{workspaceId}/alertmanager/definition:
    PUT:
      summary: Put Alert Manager Definition
      description: >-
        <p>Updates an existing alert manager definition in a workspace. If the
        workspace does not already have an alert manager definition, don't use
        this operation to create it. Instead, use
        <code>CreateAlertManagerDefinition</code>.</p>
      tags:
        - Alert Management
        - Alerts
        - Definitions
        - Identifiers
        - Managers
  /workspaces/{workspaceId}/logging:
    PUT:
      summary: Update Logging Configuration
      description: >-
        <p>Updates the log group ARN or the workspace ID of the current logging
        configuration.</p>
      tags:
        - Alert Management
        - Configurations
        - Definitions
        - Identifiers
        - Logging
        - Update
  /workspaces/{workspaceId}/rulegroupsnamespaces:
    GET:
      summary: List Rule Groups Namespaces
      description: <p>Returns a list of rule groups namespaces in a workspace.</p>
      tags:
        - Alert Management
        - Definitions
        - Groups
        - Identifiers
        - Lists
        - Logging
        - Namespaces
        - Rule Groups Namespaces
        - Rules
  /scrapers:
    GET:
      summary: List Scrapers
      description: >-
        <p>The <code>ListScrapers</code> operation lists all of the scrapers in
        your account. This includes scrapers being created or deleted. You can
        optionally filter the returned list.</p>
      tags:
        - Alert Management
        - Definitions
        - Identifiers
        - Lists
        - Logging
        - Rule Groups Namespaces
        - Scrapers
  /workspaces:
    GET:
      summary: List Workspaces
      description: >-
        <p>Lists all of the Amazon Managed Service for Prometheus workspaces in
        your account. This includes workspaces being created or deleted. </p>
      tags:
        - Alert Management
        - Definitions
        - Identifiers
        - Lists
        - Logging
        - Rule Groups Namespaces
        - Scrapers
        - Workspaces
  /workspaces/{workspaceId}/rulegroupsnamespaces/{name}:
    PUT:
      summary: Put Rule Groups Namespace
      description: >-
        <p>Updates an existing rule groups namespace within a workspace. A rule
        groups namespace is associated with exactly one rules file. A workspace
        can have multiple rule groups namespaces.</p> <p>Use this operation only
        to update existing rule groups namespaces. To create a new rule groups
        namespace, use <code>CreateRuleGroupsNamespace</code>.</p> <p>You can't
        use this operation to add tags to an existing rule groups namespace.
        Instead, use <code>TagResource</code>.</p>
      tags:
        - Alert Management
        - Definitions
        - Groups
        - Identifiers
        - Logging
        - Names
        - Namespaces
        - Rule Groups Namespaces
        - Rules
        - Scrapers
        - Workspaces
  /scrapers/{scraperId}:
    GET:
      summary: Describe Scraper
      description: >-
        <p>The <code>DescribeScraper</code> operation displays information about
        an existing scraper.</p>
      tags:
        - Alert Management
        - Definitions
        - Describe
        - Identifiers
        - Logging
        - Names
        - Rule Groups Namespaces
        - Scrapers
        - Workspaces
  /workspaces/{workspaceId}:
    GET:
      summary: Describe Workspace
      description: <p>Returns information about an existing workspace. </p>
      tags:
        - Alert Management
        - Definitions
        - Describe
        - Identifiers
        - Logging
        - Names
        - Rule Groups Namespaces
        - Scrapers
        - Workspaces
  /scraperconfiguration:
    GET:
      summary: Get Default Scraper Configuration
      description: >-
        <p>The <code>GetDefaultScraperConfiguration</code> operation returns the
        default scraper configuration used when Amazon EKS creates a scraper for
        you.</p>
      tags:
        - Alert Management
        - Configurations
        - Default
        - Definitions
        - Identifiers
        - Logging
        - Names
        - Rule Groups Namespaces
        - Scraper Configurations
        - Scrapers
        - Workspaces
  /tags/{resourceArn}:
    DELETE:
      summary: Untag Resource
      description: >-
        <p>Removes the specified tags from an Amazon Managed Service for
        Prometheus resource. The only resources that can be tagged are
        workspaces and rule groups namespaces. </p>
      tags:
        - ARN
        - Alert Management
        - Definitions
        - Identifiers
        - Logging
        - Names
        - Resources
        - Rule Groups Namespaces
        - Scraper Configurations
        - Scrapers
        - Untag
        - Workspaces
  /workspaces/{workspaceId}/alias:
    POST:
      summary: Update Workspace Alias
      description: <p>Updates the alias of an existing work
      tags:
        - ARN
        - Alert Management
        - Ali
        - Alias
        - Definitions
        - Identifiers
        - Logging
        - Names
        - Rule Groups Namespaces
        - Scraper Configurations
        - Scrapers
        - Update
        - Workspaces
