openapi: 3.1.0
info:
  title: amplify
paths:
  /apps:
    GET:
      summary: ListApps
      description: <p>Returns a list of the existing Amplify apps. </p>
      tags:
        - Lists
        - Applications
        - Applications
  /apps/{appId}/backendenvironments:
    GET:
      summary: ListBackendEnvironments
      description: <p>Lists the backend environments for an Amplify app. </p>
      tags:
        - Lists
        - Backends
        - Environments
        - Applications
        - Identifiers
        - Backend Environments
  /apps/{appId}/branches:
    GET:
      summary: ListBranches
      description: <p> Lists the branches of an Amplify app. </p>
      tags:
        - Lists
        - Branches
        - Applications
        - Identifiers
        - Backend Environments
        - Branches
  /apps/{appId}/branches/{branchName}/deployments:
    POST:
      summary: CreateDeployment
      description: >-
        <p>Creates a deployment for a manually deployed Amplify app. Manually
        deployed apps are not connected to a repository. </p> <p>The maximum
        duration between the <code>CreateDeployment</code> call and the
        <code>StartDeployment</code> call cannot exceed 8 hours. If the duration
        exceeds 8 hours, the <code>StartDeployment</code> call and the
        associated <code>Job</code> will fail.</p>
      tags:
        - Create
        - Deployments
        - Applications
        - Identifiers
        - Backend Environments
        - Branches
        - Branch
        - Names
        - Deployments
  /apps/{appId}/domains:
    GET:
      summary: ListDomainAssociations
      description: <p> Returns the domain associations for an Amplify app. </p>
      tags:
        - Lists
        - Domains
        - Associations
        - Applications
        - Identifiers
        - Backend Environments
        - Branches
        - Branch
        - Names
        - Deployments
        - Domains
  /apps/{appId}/webhooks:
    GET:
      summary: ListWebhooks
      description: <p>Returns a list of webhooks for an Amplify app. </p>
      tags:
        - Lists
        - Webhooks
        - Applications
        - Identifiers
        - Backend Environments
        - Branches
        - Branch
        - Names
        - Deployments
        - Domains
        - Webhooks
  /apps/{appId}:
    POST:
      summary: UpdateApp
      description: <p>Updates an existing Amplify app. </p>
      tags:
        - Update
        - Applications
        - Applications
        - Identifiers
        - Backend Environments
        - Branches
        - Branch
        - Names
        - Deployments
        - Domains
        - Webhooks
  /apps/{appId}/backendenvironments/{environmentName}:
    GET:
      summary: GetBackendEnvironment
      description: <p>Returns a backend environment for an Amplify app. </p>
      tags:
        - Get
        - Backends
        - Environments
        - Applications
        - Identifiers
        - Backend Environments
        - Branches
        - Branch
        - Names
        - Deployments
        - Domains
        - Webhooks
        - Environments
  /apps/{appId}/branches/{branchName}:
    POST:
      summary: UpdateBranch
      description: <p> Updates a branch for an Amplify app. </p>
      tags:
        - Update
        - Branch
        - Applications
        - Identifiers
        - Backend Environments
        - Branches
        - Branch
        - Names
        - Deployments
        - Domains
        - Webhooks
        - Environments
  /apps/{appId}/domains/{domainName}:
    POST:
      summary: UpdateDomainAssociation
      description: <p> Creates a new domain association for an Amplify app.</p>
      tags:
        - Update
        - Domains
        - Association
        - Applications
        - Identifiers
        - Backend Environments
        - Branches
        - Branch
        - Names
        - Deployments
        - Domains
        - Webhooks
        - Environments
        - Domains
  /apps/{appId}/branches/{branchName}/jobs/{jobId}:
    GET:
      summary: GetJob
      description: <p> Returns a job for a branch of an Amplify app. </p>
      tags:
        - Get
        - Jobs
        - Applications
        - Identifiers
        - Backend Environments
        - Branches
        - Branch
        - Names
        - Deployments
        - Domains
        - Webhooks
        - Environments
        - Domains
        - Jobs
        - Jobs
  /webhooks/{webhookId}:
    POST:
      summary: UpdateWebhook
      description: <p>Updates a webhook. </p>
      tags:
        - Update
        - Webhooks
        - Applications
        - Identifiers
        - Backend Environments
        - Branches
        - Branch
        - Names
        - Deployments
        - Domains
        - Webhooks
        - Environments
        - Domains
        - Jobs
        - Jobs
  /apps/{appId}/accesslogs:
    POST:
      summary: GenerateAccessLogs
      description: >-
        <p>Returns the website access logs for a specific time range using a
        presigned URL. </p>
      tags:
        - Generate
        - Access
        - Logs
        - Applications
        - Identifiers
        - Backend Environments
        - Branches
        - Branch
        - Names
        - Deployments
        - Domains
        - Webhooks
        - Environments
        - Domains
        - Jobs
        - Jobs
        - Access Logs
  /artifacts/{artifactId}:
    GET:
      summary: GetArtifactUrl
      description: <p>Returns the artifact info that corresponds to an artifact id. </p>
      tags:
        - Get
        - Artifacts
        - URL
        - Applications
        - Identifiers
        - Backend Environments
        - Branches
        - Branch
        - Names
        - Deployments
        - Domains
        - Webhooks
        - Environments
        - Domains
        - Jobs
        - Jobs
        - Access Logs
  /apps/{appId}/branches/{branchName}/jobs/{jobId}/artifacts:
    GET:
      summary: ListArtifacts
      description: >-
        <p>Returns a list of artifacts for a specified app, branch, and job.
        </p>
      tags:
        - Lists
        - Artifacts
        - Applications
        - Identifiers
        - Backend Environments
        - Branches
        - Branch
        - Names
        - Deployments
        - Domains
        - Webhooks
        - Environments
        - Domains
        - Jobs
        - Jobs
        - Access Logs
        - Artifacts
  /apps/{appId}/branches/{branchName}/jobs:
    POST:
      summary: StartJob
      description: <p> Starts a new job for a branch of an Amplify app. </p>
      tags:
        - Start
        - Jobs
        - Applications
        - Identifiers
        - Backend Environments
        - Branches
        - Branch
        - Names
        - Deployments
        - Domains
        - Webhooks
        - Environments
        - Domains
        - Jobs
        - Jobs
        - Access Logs
        - Artifacts
  /tags/{resourceArn}:
    DELETE:
      summary: UntagResource
      description: <p>Untags a resource with a specified Amazon Resource Name (ARN).</p>
      tags:
        - Untag
        - Resources
        - Applications
        - Identifiers
        - Backend Environments
        - Branches
        - Branch
        - Names
        - Deployments
        - Domains
        - Webhooks
        - Environments
        - Domains
        - Jobs
        - Jobs
        - Access Logs
        - Artifacts
        - ARN
  /apps/{appId}/branches/{branchName}/deployments/start:
    POST:
      summary: StartDeployment
      description: >-
        <p>Starts a deployment for a manually deployed app. Manually deployed
        apps are not connected to a repository. </p> <p>The maximum duration
        between the <code>CreateDeployment</code> call and the
        <code>StartDeployment</code> call cannot exceed 8 hours. If the duration
        exceeds 8 hours, the <code>StartDeployment</code> call and the
        associated <code>Job</code> will fail.</p>
      tags:
        - Start
        - Deployments
        - Applications
        - Identifiers
        - Backend Environments
        - Branches
        - Branch
        - Names
        - Deployments
        - Domains
        - Webhooks
        - Environments
        - Domains
        - Jobs
        - Jobs
        - Access Logs
        - Artifacts
        - ARN
        - Start
  /apps/{appId}/branches/{branchName}/jobs/{jobId}/stop:
    DELETE:
      summary: StopJob
      description: <p> Stops a job that is in progress for a branch of an Ampli
      tags:
        - Stop
        - Jobs
        - Applications
        - Identifiers
        - Backend Environments
        - Branches
        - Branch
        - Names
        - Deployments
        - Domains
        - Webhooks
        - Environments
        - Domains
        - Jobs
        - Jobs
        - Access Logs
        - Artifacts
        - ARN
        - Start
        - null
