openapi: 3.1.0
info:
  title: athena
paths:
  /:
    POST:
      summary: UpdateWorkGroup
      description: >-
        <p>Updates the workgroup with the specified name. The workgroup's name
        cannot be changed. Only <code>ConfigurationUpdates</code> can be spec
      tags:
        - Update
        - Work
        - null
