openapi: 3.1.0
info:
  title: autoscaling-plans
paths:
  /:
    POST:
      summary: UpdateScalingPlan
      description: >-
        <p>Updates the specified scaling plan.</p> <p>You cannot update a
        scaling plan if it is in the process of being created, updated, or de
      tags:
        - Update
        - Scaling
        - null
