openapi: 3.1.0
info:
  title: braket
paths:
  /job/{jobArn}/cancel:
    PUT:
      summary: CancelJob
      description: <p>Cancels an Amazon Braket job.</p>
      tags:
        - Cancel
        - Jobs
        - ARN
        - Cancel
  /quantum-task/{quantumTaskArn}/cancel:
    PUT:
      summary: CancelQuantumTask
      description: <p>Cancels the specified task.</p>
      tags:
        - Cancel
        - Quantum
        - Tasks
        - ARN
        - Cancel
        - Tasks
  /job:
    POST:
      summary: CreateJob
      description: <p>Creates an Amazon Braket job.</p>
      tags:
        - Create
        - Jobs
        - ARN
        - Cancel
        - Tasks
        - Jobs
  /quantum-task:
    POST:
      summary: CreateQuantumTask
      description: <p>Creates a quantum task.</p>
      tags:
        - Create
        - Quantum
        - Tasks
        - ARN
        - Cancel
        - Tasks
        - Jobs
        - Quantum
  /device/{deviceArn}:
    GET:
      summary: GetDevice
      description: >-
        <p>Retrieves the devices available in Amazon Braket.</p> <note> <p>For
        backwards compatibility with older versions of BraketSchemas, OpenQASM
        information is omitted from GetDevice API calls. To get this information
        the user-agent needs to present a recent version of the BraketSchemas
        (1.8.0 or later). The Braket SDK automatically reports this for you. If
        you do not see OpenQASM results in the GetDevice response when using a
        Braket SDK, you may need to set AWS_EXECUTION_ENV environment variable
        to configure user-agent. See the code examples provided below for how to
        do this for the AWS CLI, Boto3, and the Go, Java, and
        JavaScript/TypeScript SDKs.</p> </note>
      tags:
        - Get
        - Device
        - ARN
        - Cancel
        - Tasks
        - Jobs
        - Quantum
  /job/{jobArn}:
    GET:
      summary: GetJob
      description: <p>Retrieves the specified Amazon Braket job.</p>
      tags:
        - Get
        - Jobs
        - ARN
        - Cancel
        - Tasks
        - Jobs
        - Quantum
  /quantum-task/{quantumTaskArn}:
    GET:
      summary: GetQuantumTask
      description: <p>Retrieves the specified quantum task.</p>
      tags:
        - Get
        - Quantum
        - Tasks
        - ARN
        - Cancel
        - Tasks
        - Jobs
        - Quantum
  /tags/{resourceArn}:
    DELETE:
      summary: UntagResource
      description: <p>Remove tags from a resource.</p>
      tags:
        - Untag
        - Resources
        - ARN
        - Cancel
        - Tasks
        - Jobs
        - Quantum
  /devices:
    POST:
      summary: SearchDevices
      description: <p>Searches for devices using the specified filters.</p>
      tags:
        - Search
        - Devices
        - ARN
        - Cancel
        - Tasks
        - Jobs
        - Quantum
        - Devices
  /jobs:
    POST:
      summary: SearchJobs
      description: >-
        <p>Searches for Amazon Braket jobs that match the specified filter
        values.</p>
      tags:
        - Search
        - Jobs
        - ARN
        - Cancel
        - Tasks
        - Jobs
        - Quantum
        - Devices
        - Jobs
  /quantum-tasks:
    POST:
      summary: SearchQuantumTasks
      description: <p>Searches for tasks that match the specified filter v
      tags:
        - Search
        - Quantum
        - Tasks
        - ARN
        - Cancel
        - Tasks
        - Jobs
        - Quantum
        - Devices
        - Jobs
        - null
