openapi: 3.1.0
info:
  title: cloud9
paths:
  /:
    POST:
      summary: UpdateEnvironmentMembership
      description: >-
        <p>Changes the settings of an existing environment member for an Cloud9
        development enviro
      tags:
        - Update
        - Environments
        - Members
