openapi: 3.1.0
info:
  title: codeguru-security
paths:
  /batchGetFindings:
    POST:
      summary: BatchGetFindings
      description: <p>Returns a list of all requested findings.</p>
      tags:
        - Batches
        - Get
        - Findings
        - Get
        - Findings
  /scans:
    GET:
      summary: ListScans
      description: >-
        <p>Returns a list of all the standard scans in an account. Does not
        return express scans.</p>
      tags:
        - Lists
        - Scans
        - Get
        - Findings
        - Scans
  /uploadUrl:
    POST:
      summary: CreateUploadUrl
      description: >-
        <p>Generates a pre-signed URL and request headers used to upload a code
        resource.</p> <p>You can upload your code resource to the URL and add
        the request headers using any HTTP client.</p>
      tags:
        - Create
        - Uploads
        - URL
        - Get
        - Findings
        - Scans
        - URL
  /accountConfiguration/get:
    GET:
      summary: GetAccountConfiguration
      description: <p>Use to get account level configuration.</p>
      tags:
        - Get
        - Account
        - Configurations
        - Get
        - Findings
        - Scans
        - URL
        - Configurations
  /findings/{scanName}:
    GET:
      summary: GetFindings
      description: <p>Returns a list of all findings generated by a particular scan.</p>
      tags:
        - Get
        - Findings
        - Get
        - Findings
        - Scans
        - URL
        - Configurations
        - Names
  /metrics/summary:
    GET:
      summary: GetMetricsSummary
      description: >-
        <p>Returns top level metrics about an account from a specified date,
        including number of open findings, the categories with most findings,
        the scans with most open findings, and scans with most open critical
        findings. </p>
      tags:
        - Get
        - Metrics
        - Summaries
        - Get
        - Findings
        - Scans
        - URL
        - Configurations
        - Names
        - Metrics
        - Summaries
  /scans/{scanName}:
    GET:
      summary: GetScan
      description: >-
        <p>Returns details about a scan, including whether or not a scan has
        completed.</p>
      tags:
        - Get
        - Scans
        - Get
        - Findings
        - Scans
        - URL
        - Configurations
        - Names
        - Metrics
        - Summaries
  /metrics/findings:
    GET:
      summary: ListFindingsMetrics
      description: >-
        <p>Returns metrics about all findings in an account within a specified
        time range.</p>
      tags:
        - Lists
        - Findings
        - Metrics
        - Get
        - Findings
        - Scans
        - URL
        - Configurations
        - Names
        - Metrics
        - Summaries
  /tags/{resourceArn}:
    DELETE:
      summary: UntagResource
      description: <p>Use to remove one or more tags from an existing scan.</p>
      tags:
        - Untag
        - Resources
        - Get
        - Findings
        - Scans
        - URL
        - Configurations
        - Names
        - Metrics
        - Summaries
        - ARN
  /updateAccountConfiguration:
    PUT:
      summary: UpdateAccountConfiguration
      description: <p>Use to update account-level configuration with an encrypti
      tags:
        - Update
        - Account
        - Configurations
        - Get
        - Findings
        - Scans
        - URL
        - Configurations
        - Names
        - Metrics
        - Summaries
        - ARN
        - null
