openapi: 3.1.0
info:
  title: codeguruprofiler
paths:
  /profilingGroups/{profilingGroupName}/notificationConfiguration:
    GET:
      summary: GetNotificationConfiguration
      description: >-
        <p>Get the current configuration for anomaly notifications for a
        profiling group.</p>
      tags:
        - Get
        - Notifications
        - Configurations
        - Groups
        - Profiling
        - Group
        - Names
        - Notifications
        - Configurations
  /profilingGroups/{profilingGroupName}/frames/-/metrics:
    POST:
      summary: BatchGetFrameMetricData
      description: >-
        <p> Returns the time series of values for a requested list of frame
        metrics from a time period.</p>
      tags:
        - Batches
        - Get
        - Frames
        - Metrics
        - Data
        - Groups
        - Profiling
        - Group
        - Names
        - Notifications
        - Configurations
        - Frames
        - Metrics
  /profilingGroups/{profilingGroupName}/configureAgent:
    POST:
      summary: ConfigureAgent
      description: >-
        <p> Used by profiler agents to report their current state and to receive
        remote configuration updates. For example, <code>ConfigureAgent</code>
        can be used to tell an agent whether to profile or not and for how long
        to return profiling data. </p>
      tags:
        - Configure
        - Agent
        - Groups
        - Profiling
        - Group
        - Names
        - Notifications
        - Configurations
        - Frames
        - Metrics
        - Configure
        - Agent
  /profilingGroups:
    GET:
      summary: ListProfilingGroups
      description: >-
        <p> Returns a list of profiling groups. The profiling groups are
        returned as <a
        href="https://docs.aws.amazon.com/codeguru/latest/profiler-api/API_ProfilingGroupDescription.html">
        <code>ProfilingGroupDescription</code> </a> objects. </p>
      tags:
        - Lists
        - Profiling
        - Groups
        - Groups
        - Profiling
        - Group
        - Names
        - Notifications
        - Configurations
        - Frames
        - Metrics
        - Configure
        - Agent
  /profilingGroups/{profilingGroupName}:
    PUT:
      summary: UpdateProfilingGroup
      description: <p>Updates a profiling group.</p>
      tags:
        - Update
        - Profiling
        - Group
        - Groups
        - Profiling
        - Group
        - Names
        - Notifications
        - Configurations
        - Frames
        - Metrics
        - Configure
        - Agent
  /internal/findingsReports:
    GET:
      summary: GetFindingsReportAccountSummary
      description: >-
        <p> Returns a list of <a
        href="https://docs.aws.amazon.com/codeguru/latest/profiler-api/API_FindingsReportSummary.html">
        <code>FindingsReportSummary</code> </a> objects that contain analysis
        results for all profiling groups in your AWS account. </p>
      tags:
        - Get
        - Findings
        - Reports
        - Account
        - Summaries
        - Groups
        - Profiling
        - Group
        - Names
        - Notifications
        - Configurations
        - Frames
        - Metrics
        - Configure
        - Agent
        - Reports
  /profilingGroups/{profilingGroupName}/policy:
    GET:
      summary: GetPolicy
      description: >-
        <p> Returns the JSON-formatted resource-based policy on a profiling
        group. </p>
      tags:
        - Get
        - Policies
        - Groups
        - Profiling
        - Group
        - Names
        - Notifications
        - Configurations
        - Frames
        - Metrics
        - Configure
        - Agent
        - Reports
        - Policies
  /profilingGroups/{profilingGroupName}/profile:
    GET:
      summary: GetProfile
      description: >-
        <p> Gets the aggregated profile of a profiling group for a specified
        time range. Amazon CodeGuru Profiler collects posted agent profiles for
        a profiling group into aggregated profiles. </p> <pre><code>
        &lt;note&gt; &lt;p&gt; Because aggregated profiles expire over time
        &lt;code&gt;GetProfile&lt;/code&gt; is not idempotent. &lt;/p&gt;
        &lt;/note&gt; &lt;p&gt; Specify the time range for the requested
        aggregated profile using 1 or 2 of the following parameters:
        &lt;code&gt;startTime&lt;/code&gt;, &lt;code&gt;endTime&lt;/code&gt;,
        &lt;code&gt;period&lt;/code&gt;. The maximum time range allowed is 7
        days. If you specify all 3 parameters, an exception is thrown. If you
        specify only &lt;code&gt;period&lt;/code&gt;, the latest aggregated
        profile is returned. &lt;/p&gt; &lt;p&gt; Aggregated profiles are
        available with aggregation periods of 5 minutes, 1 hour, and 1 day,
        aligned to UTC. The aggregation period of an aggregated profile
        determines how long it is retained. For more information, see &lt;a
        href=&quot;https://docs.aws.amazon.com/codeguru/latest/profiler-api/API_AggregatedProfileTime.html&quot;&gt;
        &lt;code&gt;AggregatedProfileTime&lt;/code&gt; &lt;/a&gt;. The
        aggregated profile's aggregation period determines how long it is
        retained by CodeGuru Profiler. &lt;/p&gt; &lt;ul&gt; &lt;li&gt;
        &lt;p&gt; If the aggregation period is 5 minutes, the aggregated profile
        is retained for 15 days. &lt;/p&gt; &lt;/li&gt; &lt;li&gt; &lt;p&gt; If
        the aggregation period is 1 hour, the aggregated profile is retained for
        60 days. &lt;/p&gt; &lt;/li&gt; &lt;li&gt; &lt;p&gt; If the aggregation
        period is 1 day, the aggregated profile is retained for 3 years.
        &lt;/p&gt; &lt;/li&gt; &lt;/ul&gt; &lt;p&gt;There are two use cases for
        calling &lt;code&gt;GetProfile&lt;/code&gt;.&lt;/p&gt; &lt;ol&gt;
        &lt;li&gt; &lt;p&gt; If you want to return an aggregated profile that
        already exists, use &lt;a
        href=&quot;https://docs.aws.amazon.com/codeguru/latest/profiler-api/API_ListProfileTimes.html&quot;&gt;
        &lt;code&gt;ListProfileTimes&lt;/code&gt; &lt;/a&gt; to view the time
        ranges of existing aggregated profiles. Use them in a
        &lt;code&gt;GetProfile&lt;/code&gt; request to return a specific,
        existing aggregated profile. &lt;/p&gt; &lt;/li&gt; &lt;li&gt; &lt;p&gt;
        If you want to return an aggregated profile for a time range that
        doesn't align with an existing aggregated profile, then CodeGuru
        Profiler makes a best effort to combine existing aggregated profiles
        from the requested time range and return them as one aggregated profile.
        &lt;/p&gt; &lt;p&gt; If aggregated profiles do not exist for the full
        time range requested, then aggregated profiles for a smaller time range
        are returned. For example, if the requested time range is from 00:00 to
        00:20, and the existing aggregated profiles are from 00:15 and 00:25,
        then the aggregated profiles from 00:15 to 00:20 are returned.
        &lt;/p&gt; &lt;/li&gt; &lt;/ol&gt; </code></pre>
      tags:
        - Get
        - Profiles
        - Groups
        - Profiling
        - Group
        - Names
        - Notifications
        - Configurations
        - Frames
        - Metrics
        - Configure
        - Agent
        - Reports
        - Policies
        - Profiles
  /internal/profilingGroups/{profilingGroupName}/recommendations:
    GET:
      summary: GetRecommendations
      description: >-
        <p> Returns a list of <a
        href="https://docs.aws.amazon.com/codeguru/latest/profiler-api/API_Recommendation.html">
        <code>Recommendation</code> </a> objects that contain recommendations
        for a profiling group for a given time period. A list of <a
        href="https://docs.aws.amazon.com/codeguru/latest/profiler-api/API_Anomaly.html">
        <code>Anomaly</code> </a> objects that contains details about anomalies
        detected in the profiling group for the same time period is also
        returned. </p>
      tags:
        - Get
        - Recommendations
        - Groups
        - Profiling
        - Group
        - Names
        - Notifications
        - Configurations
        - Frames
        - Metrics
        - Configure
        - Agent
        - Reports
        - Policies
        - Profiles
        - Recommendations
  /internal/profilingGroups/{profilingGroupName}/findingsReports:
    GET:
      summary: ListFindingsReports
      description: >-
        <p>List the available reports for a given profiling group and time
        range.</p>
      tags:
        - Lists
        - Findings
        - Reports
        - Groups
        - Profiling
        - Group
        - Names
        - Notifications
        - Configurations
        - Frames
        - Metrics
        - Configure
        - Agent
        - Reports
        - Policies
        - Profiles
        - Recommendations
        - Findings
  /profilingGroups/{profilingGroupName}/profileTimes:
    GET:
      summary: ListProfileTimes
      description: >-
        <p>Lists the start times of the available aggregated profiles of a
        profiling group for an aggregation period within the specified time
        range.</p>
      tags:
        - Lists
        - Profiles
        - Times
        - Groups
        - Profiling
        - Group
        - Names
        - Notifications
        - Configurations
        - Frames
        - Metrics
        - Configure
        - Agent
        - Reports
        - Policies
        - Profiles
        - Recommendations
        - Findings
        - Times
  /tags/{resourceArn}:
    DELETE:
      summary: UntagResource
      description: <p> Use to remove one or more tags from a resource. </p>
      tags:
        - Untag
        - Resources
        - Groups
        - Profiling
        - Group
        - Names
        - Notifications
        - Configurations
        - Frames
        - Metrics
        - Configure
        - Agent
        - Reports
        - Policies
        - Profiles
        - Recommendations
        - Findings
        - Times
        - ARN
  /profilingGroups/{profilingGroupName}/agentProfile:
    POST:
      summary: PostAgentProfile
      description: >-
        <p> Submits profiling data to an aggregated profile of a profiling
        group. To get an aggregated profile that is created with this profiling
        data, use <a
        href="https://docs.aws.amazon.com/codeguru/latest/profiler-api/API_GetProfile.html">
        <code>GetProfile</code> </a>. </p>
      tags:
        - Posts
        - Agent
        - Profiles
        - Groups
        - Profiling
        - Group
        - Names
        - Notifications
        - Configurations
        - Frames
        - Metrics
        - Configure
        - Agent
        - Reports
        - Policies
        - Profiles
        - Recommendations
        - Findings
        - Times
        - ARN
  /profilingGroups/{profilingGroupName}/policy/{actionGroup}:
    DELETE:
      summary: RemovePermission
      description: >-
        <p> Removes permissions from a profiling group's resource-based policy
        that are provided using an action group. The one supported action group
        that can be removed is <code>agentPermission</code> which grants
        <code>ConfigureAgent</code> and <code>PostAgent</code> permissions. For
        more information, see <a
        href="https://docs.aws.amazon.com/codeguru/latest/profiler-ug/resource-based-policies.html">Resource-based
        policies in CodeGuru Profiler</a> in the <i>Amazon CodeGuru Profiler
        User Guide</i>, <a
        href="https://docs.aws.amazon.com/codeguru/latest/profiler-api/API_ConfigureAgent.html">
        <code>ConfigureAgent</code> </a>, and <a
        href="https://docs.aws.amazon.com/codeguru/latest/profiler-api/API_PostAgentProfile.html">
        <code>PostAgentProfile</code> </a>. </p>
      tags:
        - Removes
        - Permission
        - Groups
        - Profiling
        - Group
        - Names
        - Notifications
        - Configurations
        - Frames
        - Metrics
        - Configure
        - Agent
        - Reports
        - Policies
        - Profiles
        - Recommendations
        - Findings
        - Times
        - ARN
        - Actions
  /profilingGroups/{profilingGroupName}/notificationConfiguration/{channelId}:
    DELETE:
      summary: RemoveNotificationChannel
      description: <p>Remove one anomaly notifications channel for a profiling group.</p>
      tags:
        - Removes
        - Notifications
        - Channels
        - Groups
        - Profiling
        - Group
        - Names
        - Notifications
        - Configurations
        - Frames
        - Metrics
        - Configure
        - Agent
        - Reports
        - Policies
        - Profiles
        - Recommendations
        - Findings
        - Times
        - ARN
        - Actions
        - Channels
        - Identifiers
  /internal/profilingGroups/{profilingGroupName}/anomalies/{anomalyInstanceId}/feedback:
    POST:
      summary: SubmitFeedback
      description: >-
        <p>Sends feedback to CodeGuru Profiler about whether the anomaly
        detected by the analysis is useful o
      tags:
        - Submit
        - Feedback
        - Groups
        - Profiling
        - Group
        - Names
        - Notifications
        - Configurations
        - Frames
        - Metrics
        - Configure
        - Agent
        - Reports
        - Policies
        - Profiles
        - Recommendations
        - Findings
        - Times
        - ARN
        - Actions
        - Channels
        - Identifiers
        - Anomalies
        - Anomaly
        - Instances
        - Feedback
