openapi: 3.1.0
info:
  title: codeguru-reviewer
paths:
  /associations:
    GET:
      summary: ListRepositoryAssociations
      description: >-
        <p>Returns a list of <a
        href="https://docs.aws.amazon.com/codeguru/latest/reviewer-api/API_RepositoryAssociationSummary.html">RepositoryAssociationSummary</a>
        objects that contain summary information about a repository association.
        You can filter the returned list by <a
        href="https://docs.aws.amazon.com/codeguru/latest/reviewer-api/API_RepositoryAssociationSummary.html#reviewer-Type-RepositoryAssociationSummary-ProviderType">ProviderType</a>,
        <a
        href="https://docs.aws.amazon.com/codeguru/latest/reviewer-api/API_RepositoryAssociationSummary.html#reviewer-Type-RepositoryAssociationSummary-Name">Name</a>,
        <a
        href="https://docs.aws.amazon.com/codeguru/latest/reviewer-api/API_RepositoryAssociationSummary.html#reviewer-Type-RepositoryAssociationSummary-State">State</a>,
        and <a
        href="https://docs.aws.amazon.com/codeguru/latest/reviewer-api/API_RepositoryAssociationSummary.html#reviewer-Type-RepositoryAssociationSummary-Owner">Owner</a>.</p>
      tags:
        - Lists
        - Repositories
        - Associations
        - Associations
  /codereviews:
    GET:
      summary: ListCodeReviews
      description: >-
        <p>Lists all the code reviews that the customer has created in the past
        90 days.</p>
      tags:
        - Lists
        - Code
        - Reviews
        - Associations
        - Code Reviews
  /codereviews/{CodeReviewArn}:
    GET:
      summary: DescribeCodeReview
      description: >-
        <p>Returns the metadata associated with the code review along with its
        status.</p>
      tags:
        - Describe
        - Code
        - Reviews
        - Associations
        - Code Reviews
        - Code
        - Reviews
        - ARN
  /feedback/{CodeReviewArn}:
    GET:
      summary: DescribeRecommendationFeedback
      description: >-
        <p>Describes the customer feedback for a CodeGuru Reviewer
        recommendation.</p>
      tags:
        - Describe
        - Recommendations
        - Feedback
        - Associations
        - Code Reviews
        - Code
        - Reviews
        - ARN
  /associations/{AssociationArn}:
    DELETE:
      summary: DisassociateRepository
      description: >-
        <p>Removes the association between Amazon CodeGuru Reviewer and a
        repository.</p>
      tags:
        - Disassociate
        - Repositories
        - Associations
        - Code Reviews
        - Code
        - Reviews
        - ARN
        - Association
  /feedback/{CodeReviewArn}/RecommendationFeedback:
    GET:
      summary: ListRecommendationFeedback
      description: >-
        <p>Returns a list of <a
        href="https://docs.aws.amazon.com/codeguru/latest/reviewer-api/API_RecommendationFeedbackSummary.html">RecommendationFeedbackSummary</a>
        objects that contain customer recommendation feedback for all CodeGuru
        Reviewer users.</p>
      tags:
        - Lists
        - Recommendations
        - Feedback
        - Associations
        - Code Reviews
        - Code
        - Reviews
        - ARN
        - Association
        - Recommendations
        - Feedback
  /codereviews/{CodeReviewArn}/Recommendations:
    GET:
      summary: ListRecommendations
      description: >-
        <p>Returns the list of all recommendations for a completed code
        review.</p>
      tags:
        - Lists
        - Recommendations
        - Associations
        - Code Reviews
        - Code
        - Reviews
        - ARN
        - Association
        - Recommendations
        - Feedback
        - Recommendations
  /tags/{resourceArn}:
    DELETE:
      summary: UntagResource
      description: <p>Removes a tag from an associated repository.</p>
      tags:
        - Untag
        - Resources
        - Associations
        - Code Reviews
        - Code
        - Reviews
        - ARN
        - Association
        - Recommendations
        - Feedback
        - Recommendations
  /feedback:
    PUT:
      summary: PutRecommendationFeedback
      description: >-
        <p>Stores customer feedback for a CodeGuru Reviewer recommendation. When
        this API is called again with different reactions the previous feedback
        is overwr
      tags:
        - Put
        - Recommendations
        - Feedback
        - Associations
        - Code Reviews
        - Code
        - Reviews
        - ARN
        - Association
        - Recommendations
        - Feedback
        - Recommendations
