openapi: 3.1.0
info:
  title: codedeploy
paths:
  /:
    POST:
      summary: UpdateDeploymentGroup
      description: <p>Changes information about a deployment
      tags:
        - Update
        - Deployments
        - null
