openapi: 3.1.0
info:
  title: comprehendmedical
paths:
  /:
    POST:
      summary: StopSNOMEDCTInferenceJob
      description: <p> Stops an InferSNOMEDCT inference job in pro
      tags:
        - Stop
        - Inference
        - Items
